config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :characters
    resources :races
    resources :professions
    resources :items
    resources :properties
    resources :relatives
    resources :skills
    resources :users
    resources :sessions

    root to: "characters#index"
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'reg_admin', to: 'sessions#reg_admin'

  root to: "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :race

  has_many :professions

  has_many :items
  has_many :skills
  has_many :relatives
  has_many :properties

  mount_uploader :avatar, AvatarUploader
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :character

  enum kind: { money: 0, item: 1, weapon: 2, artifact: 3 }
end

app/models/profession.rb
class Profession < ApplicationRecord
  belongs_to :character
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :character

  enum kind: { transport: 0, real_estate: 1, moveable: 2 }
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :characters
end

app/models/relative.rb
class Relative < ApplicationRecord
  belongs_to :character
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :character

  enum kind: { race: 0, physical: 1, magical: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  has_many :characters

  mount_uploader :avatar, AvatarUploader

  enum lang: { en: 0, ru: 1, uk: 2 }

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :require_login

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end

    def require_login
      super
      Current.user = current_user
      I18n.locale = current_user&.lang || 'en'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attitudes_helper.rb
module AttitudesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/application/_flashes.html.erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <% next unless value.respond_to?(:html_safe) %>
      <div class="flash flash-<%= key %>"><%= value.html_safe %></div>
    <% end -%>
  </div>
<% end %>

app/views/admin/application/_icons.html.erb
<svg hidden xmlns="http://www.w3.org/2000/svg">
  <symbol id="icon-cancel" viewBox="0 0 48 48">
    <path fill-rule="evenodd" d="M24 19.757l-8.485-8.485c-.784-.783-2.047-.782-2.827 0l-1.417 1.416c-.777.777-.78 2.046.002 2.827L19.757 24l-8.485 8.485c-.783.784-.782 2.047 0 2.827l1.416 1.417c.777.777 2.046.78 2.827-.002L24 28.243l8.485 8.485c.784.783 2.047.782 2.827 0l1.417-1.416c.777-.777.78-2.046-.002-2.827L28.243 24l8.485-8.485c.783-.784.782-2.047 0-2.827l-1.416-1.417c-.777-.777-2.046-.78-2.827.002L24 19.757zM24 47c12.703 0 23-10.297 23-23S36.703 1 24 1 1 11.297 1 24s10.297 23 23 23z" />
  </symbol>

  <symbol id="icon-eyeglass" viewBox="0 0 48 48">
    <path d="M27.885 32.515c-2.864 1.966-6.333 3.116-10.07 3.116C7.976 35.63 0 27.656 0 17.817 0 7.976 7.976 0 17.816 0S35.63 7.976 35.63 17.816c0 3.736-1.15 7.205-3.115 10.07l14.53 14.53c1.278 1.277 1.275 3.352 0 4.628-1.28 1.278-3.353 1.278-4.63 0l-14.53-14.53zm-10.07-3.736c6.056 0 10.964-4.91 10.964-10.964 0-6.055-4.91-10.964-10.964-10.964-6.055 0-10.964 4.91-10.964 10.964 0 6.055 4.91 10.963 10.964 10.963z" />
  </symbol>

  <symbol id="icon-up-caret" viewBox="0 0 48 48">
    <path d="M2.988 33.02c-1.66 0-1.943-.81-.618-1.824l20-15.28c.878-.672 2.31-.67 3.188 0l20.075 15.288c1.316 1.003 1.048 1.816-.62 1.816H2.987z" />
  </symbol>
</svg>

app/views/admin/application/_javascript.html.erb
<%#
# Javascript Partial

This partial imports the necessary javascript on each page.
By default, it includes the application JS,
but each page can define additional JS sources
by providing a `content_for(:javascript)` block.
%>

<% Administrate::Engine.javascripts.each do |js_path| %>
  <%= javascript_include_tag js_path %>
<% end %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>
<div class="nav-aside">
  <nav class="navigation" role="navigation">
    <% Administrate::Namespace.new(namespace).resources_with_index_route.each do |resource| %>
      <%= link_to(
        display_resource_name(resource),
        resource_index_route(resource),
        class: "navigation__link navigation__link--#{nav_link_state(resource)}"
      ) if accessible_action?(model_from_resource(resource), :index) %>
    <% end %>
  </nav>

  <div class="log-menu">
    <%= I18n.t('message.hello') %>, <%= link_to current_user.username, admin_user_path(current_user.id), class: "username" %>!
    <%= link_to I18n.t('message.logout'), logout_path, class: 'button mt-1' %>
  </div>
</div>

<style>
  .nav-aside {
    display: flex;
    flex-direction: column;
    justify-items: space-between;
  }
  .mt-1 {
    margin-top: 10px;
  }
  .navigation__link {
    text-decoration: none;
  }
  .username {
    text-decoration: none;
    color: #293f54;
  }
</style>

app/views/admin/application/_stylesheet.html.erb
<%#
# Stylesheet Partial

This partial imports the necessary stylesheets on each page.
By default, it includes the application CSS,
but each page can define additional CSS sources
by providing a `content_for(:stylesheet)` block.
%>

<% Administrate::Engine.stylesheets.each do |css_path| %>
  <%= stylesheet_link_tag css_path %>
<% end %>

<%= yield :stylesheet %>