config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :characters
    resources :races
    resources :professions
    resources :items
    resources :properties
    resources :relatives
    resources :skills
    resources :users
    resources :sessions

    root to: "characters#index"
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'reg_admin', to: 'sessions#reg_admin'

  root to: "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :race

  has_many :professions

  has_many :items
  has_many :skills
  has_many :relatives
  has_many :properties

  mount_uploader :avatar, AvatarUploader
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :character

  enum kind: { money: 0, item: 1, weapon: 2, artifact: 3 }
end

app/models/profession.rb
class Profession < ApplicationRecord
  belongs_to :character
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :character

  enum kind: { transport: 0, real_estate: 1, moveable: 2 }
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :characters
end

app/models/relative.rb
class Relative < ApplicationRecord
  belongs_to :character
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :character

  enum kind: { race: 0, physical: 1, magical: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  has_many :characters

  mount_uploader :avatar, AvatarUploader

  enum lang: { en: 0, ru: 1, uk: 2 }

end

app/controllers/admin/professions_controller.rb
module Admin
  class ProfessionsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attitudes_helper.rb
module AttitudesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fields/professions/_form.html.erb
<%#
# HasMany Form Partial

This partial renders an input element for has_many relationships.
By default, the input is a collection select box
that displays all possible records to associate with.
The collection select box supports multiple inputs,
and is augmented with [Selectize].

## Local variables:

- `f`:
  A Rails form generator, used to help create the appropriate input fields.
- `field`:
  An instance of [Administrate::Field::HasMany][1].
  Contains helper methods for displaying a collection select box.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Field/HasMany
[Selectize]: http://brianreavis.github.io/selectize.js
%>

<div class="field-unit__label">
  <%= f.label field.attribute, for: "#{f.object_name}_#{field.attribute_key}" %>
</div>
<div class="field-unit__field">
  <%= f.select(field.attribute_key, nil, {}, multiple: true) do %>
    <%= options_for_select(field.associated_resource_options, field.selected_options) %>
  <% end %>
</div>

app/views/fields/professions/_index.html.erb
<%#
# HasMany Index Partial

This partial renders a has_many relationship,
to be displayed on a resource's index page.

By default, the relationship is rendered
as a count of how many objects are associated through the relationship.

## Local variables:

- `field`:
  An instance of [Administrate::Field::HasMany][1].
  A wrapper around the has_many relationship pulled from the database.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Field/HasMany
%>

<%= pluralize(field.data.size, t("activerecord.models.#{field.attribute.to_s.singularize}", default: field.attribute.to_s.humanize.downcase.singularize, count: field.data.size)) %>

app/views/fields/professions/_show.html.erb
<%#
# HasMany Show Partial

This partial renders a has_many relationship,
to be displayed on a resource's show page.

By default, the relationship is rendered
as a table of the first few associated resources.
The columns of the table are taken
from the associated resource class's dashboard.

## Local variables:

- `field`:
  An instance of [Administrate::Field::HasMany][1].
  Contains methods to help display a table of associated resources.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Field/HasMany
%>

<% if field.resources.any? %>
  <% order = field.order_from_params(params.fetch(field.name, {})) %>
  <% page_number = params.fetch(field.name, {}).fetch(:page, nil) %>

  <% length = field.resources(page_number, order).length - 1 %>
  <% field.resources(page_number, order).each_with_index do |prof, i| %>
    <% comma = length == i ? "" : ",  "%>
    <%= link_to "#{prof.title} (#{prof.level})#{comma}", admin_profession_path(prof) %>
  <% end %>

  <% if field.more_than_limit? %>
    <%= paginate field.resources(page_number), param_name: "#{field.name}[page]" %>
  <% end %>

<% else %>
  <%= t("administrate.fields.has_many.none", default: "–") %>
<% end %>